apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: testdeploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: firstdeploy
  template:
    metadata:
      labels:
        app: firstdeploy
    spec:
      containers:
      - image: nginx
        name: nginx
